<center><b>Python Lab Assignment</b></center>

Name: **Shubh Routh**

Student ID: **0627431**

In [54]:
##### Imports

import pandas as pd
import numpy as np

In [55]:
#### Data Loading & Understanding

### TASK 1:- Load both datasets and display the first 5 rows.

## DATASET 1

df1 = pd.read_csv("German-Credit_1.csv")

print("First 5 Rows of Dataset 1")
display(df1.head())

First 5 Rows of Dataset 1

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
0,1,6.0,0.0,0.0,0.0,1.0,0.0,0.0,1169.0,4.0,...,0.0,67.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,1.0
1,2,48.0,0.0,0.0,0.0,1.0,0.0,0.0,5951.0,2.0,...,0.0,22.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
2,3,12.0,0.0,0.0,0.0,0.0,1.0,0.0,2096.0,2.0,...,0.0,49.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,0.0,45.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0
4,5,24.0,1.0,0.0,0.0,0.0,0.0,0.0,4870.0,3.0,...,1.0,53.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0

In [56]:
## DATASET 2

df2 = pd.read_csv("German-Credit_2.csv")

print("First 5 Rows of Dataset 2")
display(df2.head())

First 5 Rows of Dataset 2

   OBS  CHK_ACCT  HISTORY  SAV_ACCT  EMPLOYMENT  PRESENT_RESIDENT  JOB
0    1         0        4         4           4                 4    2
1    2         1        2         0           2                 2    2
2    3         3        4         0           3                 3    1
3    4         0        2         0           3                 4    2
4    5         0        3         0           2                 4    2

In [57]:
### TASK 2:- Check the shape of both datasets

print("Shape of Dataset 1:", df1.shape)
print("Shape of Dataset 2:", df2.shape)

Shape of Dataset 1: (1000, 23)
Shape of Dataset 2: (1000, 7)

In [58]:
### TASK 3:- Display column names and identify numerical features.

## COLUMN NAMES

# DATASET 1

print("\nColumns in Dataset 1")
print(df1.columns.tolist())

Columns in Dataset 1
['OBS', 'DURATION', 'NEW_CAR', 'USED_CAR', 'FURNITURE', 'RADIO_TV', 'EDUCATION', 'RETRAINING', 'AMOUNT', 'INSTALL_RATE', 'CO_APPLICANT', 'GUARANTOR', 'REAL_ESTATE', 'PROP_UNKN_NONE', 'AGE', 'OTHER_INSTALL', 'RENT', 'OWN_RES', 'NUM_CREDITS', 'NUM_DEPENDENTS', 'TELEPHONE', 'FOREIGN', 'RESPONSE']

In [59]:
# DATASET 2

print("\nColumns in Dataset 2")
print(df2.columns.tolist())

Columns in Dataset 2
['OBS', 'CHK_ACCT', 'HISTORY', 'SAV_ACCT', 'EMPLOYMENT', 'PRESENT_RESIDENT', 'JOB']

In [60]:
## NUMERICAL FEATURES

# DATASET 1

print("\nNumerical Features in Dataset 1")
print(df1.select_dtypes(include=np.number).columns.tolist())

Numerical Features in Dataset 1
['OBS', 'DURATION', 'NEW_CAR', 'USED_CAR', 'FURNITURE', 'RADIO_TV', 'EDUCATION', 'RETRAINING', 'AMOUNT', 'INSTALL_RATE', 'CO_APPLICANT', 'GUARANTOR', 'REAL_ESTATE', 'PROP_UNKN_NONE', 'AGE', 'OTHER_INSTALL', 'RENT', 'OWN_RES', 'NUM_CREDITS', 'NUM_DEPENDENTS', 'TELEPHONE', 'FOREIGN', 'RESPONSE']

In [61]:
# DATASET 2

print("\nNumerical Features in Dataset 2")
print(df2.select_dtypes(include=np.number).columns.tolist())

Numerical Features in Dataset 2
['OBS', 'CHK_ACCT', 'HISTORY', 'SAV_ACCT', 'EMPLOYMENT', 'PRESENT_RESIDENT', 'JOB']

In [62]:
### TASK 4:- Use info() to check missing values.

## DATASET 1

print("\nDataset 1 Information")
df1.info()

Dataset 1 Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBS             1000 non-null   int64
 1   DURATION        998 non-null    float64
 2   NEW_CAR         999 non-null    float64
 3   USED_CAR        999 non-null    float64
 4   FURNITURE       999 non-null    float64
 5   RADIO_TV        997 non-null    float64
 6   EDUCATION       996 non-null    float64
 7   RETRAINING      996 non-null    float64
 8   AMOUNT          990 non-null    float64
 9   INSTALL_RATE    993 non-null    float64
 10  CO_APPLICANT    992 non-null    float64
 11  GUARANTOR       993 non-null    float64
 12  REAL_ESTATE     993 non-null    float64
 13  PROP_UNKN_NONE  993 non-null    float64
 14  AGE             990 non-null    float64
 15  OTHER_INSTALL   991 non-null    float64
 16  RENT            992 non-null    float64
 17  OWN_RES         993 non-null    float64
 18  NUM_CREDITS     994 non-null    float64
 19  NUM_DEPENDENTS  993 non-null    float64
 20  TELEPHONE       995 non-null    float64
 21  FOREIGN         994 non-null    float64
 22  RESPONSE        997 non-null    float64
dtypes: float64(22), int64(1)
memory usage: 179.8 KB

In [63]:
## DATASET 2

print("\nDataset 2 Information")
df2.info()

Dataset 2 Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OBS               1000 non-null   int64
 1   CHK_ACCT          1000 non-null   int64
 2   HISTORY           1000 non-null   int64
 3   SAV_ACCT          1000 non-null   int64
 4   EMPLOYMENT        1000 non-null   int64
 5   PRESENT_RESIDENT  1000 non-null   int64
 6   JOB               1000 non-null   int64
dtypes: int64(7)
memory usage: 54.8 KB

In [64]:
#### Data Exploration

### TASK 1:- Find the average credit amount (AMOUNT).

print("Average Credit Amount =",
      df1["AMOUNT"].mean())

Average Credit Amount = 3273.168686868687

In [65]:
### TASK 2:- Find the maximum and minimum AGE.

print("Maximum Age =", df1["AGE"].max())

print("Minimum Age =", df1["AGE"].min())

Maximum Age = 75.0
Minimum Age = 19.0

In [66]:
### TASK 3:- Count customers with RESPONSE = 1

response_count = (df1["RESPONSE"] == 1).sum()
print("Customers with RESPONSE = 1 =", response_count)

Customers with RESPONSE = 1 = 698

In [67]:
### TASK 4:- Find the distribution of INSTALL_RATE

print("Distribution of INSTALL_RATE")
print(df1["INSTALL_RATE"].value_counts())

Distribution of INSTALL_RATE
INSTALL_RATE
4.0    473
2.0    230
3.0    155
1.0    135
Name: count, dtype: int64

In [68]:
#### Data Manipulation

### TASK 1:- Create a new column: AMOUNT_PER_DURATION

df1["AMOUNT_PER_DURATION"] = df1["AMOUNT"] / df1["DURATION"]
print("AMOUNT_PER_DURATION")
display(df1[["AMOUNT", "DURATION", "AMOUNT_PER_DURATION"]].head())

AMOUNT_PER_DURATION

   AMOUNT  DURATION  AMOUNT_PER_DURATION
0  1169.0       6.0           194.833333
1  5951.0      48.0           123.979167
2  2096.0      12.0           174.666667
3  7882.0      42.0           187.666667
4  4870.0      24.0           202.916667

In [69]:
### TASK 2:- Filter customers with AGE > 40 and AMOUNT > 5000

filtered_data = df1[ (df1["AGE"] > 40) & (df1["AMOUNT"] > 5000) ]
print("Filtered Customers")
display(filtered_data.head())

print("Total Matching Customers:", len(filtered_data))

Filtered Customers

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE,AMOUNT_PER_DURATION
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,45.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,187.666667
18,19,24.0,0.0,1.0,0.0,0.0,0.0,0.0,12579.0,4.0,...,44.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,524.125000
29,30,60.0,0.0,0.0,0.0,0.0,0.0,1.0,6836.0,3.0,...,63.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,0.0,113.933333
42,43,18.0,0.0,0.0,0.0,0.0,0.0,0.0,6204.0,2.0,...,44.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,1.0,344.666667
44,45,48.0,0.0,1.0,0.0,0.0,0.0,0.0,6143.0,4.0,...,58.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,127.979167

Total Matching Customers: 60

In [70]:
### TASK 3:- Sort data based on AMOUNT (descending)

sorted_data = df1.sort_values( by="AMOUNT", ascending=False )
print("Top 10 Customers by Amount")
display(sorted_data.head(10))

Top 10 Customers by Amount

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE,AMOUNT_PER_DURATION
915,916,48.0,0.0,0.0,0.0,0.0,0.0,0.0,18424.0,1.0,...,32.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,383.833333
95,96,54.0,0.0,0.0,0.0,0.0,0.0,1.0,15945.0,3.0,...,58.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,295.277778
818,819,36.0,0.0,0.0,0.0,0.0,0.0,0.0,15857.0,2.0,...,43.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,440.472222
887,888,48.0,0.0,0.0,0.0,0.0,0.0,1.0,15672.0,2.0,...,23.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,326.500000
637,638,60.0,0.0,0.0,0.0,1.0,0.0,0.0,15653.0,2.0,...,21.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,1.0,260.883333
917,918,6.0,1.0,0.0,0.0,0.0,0.0,0.0,14896.0,1.0,...,68.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,2482.666667
374,375,60.0,0.0,0.0,0.0,0.0,0.0,0.0,14782.0,3.0,...,60.0,1.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,246.366667
236,237,6.0,1.0,0.0,0.0,0.0,0.0,0.0,14555.0,1.0,...,23.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,2425.833333
63,64,48.0,0.0,0.0,0.0,0.0,0.0,1.0,14421.0,2.0,...,25.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,300.437500
378,379,36.0,1.0,0.0,0.0,0.0,0.0,0.0,14318.0,4.0,...,57.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,397.722222

In [71]:
#### Grouping & Analysis

### TASK 1:- Group by RESPONSE and find mean AMOUNT

group_amount = df1.groupby("RESPONSE")["AMOUNT"].mean()
print("Mean Amount by RESPONSE")
print(group_amount)

Mean Amount by RESPONSE
RESPONSE
0.0    3946.831081
1.0    2986.940837
Name: AMOUNT, dtype: float64

In [72]:
### TASK 2:- Find average AGE for each RESPONSE

group_age = df1.groupby("RESPONSE")["AGE"].mean()
print("Average Age by RESPONSE")
print(group_age)

Average Age by RESPONSE
RESPONSE
0.0    33.787162
1.0    36.207792
Name: AGE, dtype: float64

In [73]:
#### Merging & Advanced

### TASK 1:- Merge both datasets using OBS column.

merged_df = pd.merge( df1, df2, on="OBS" )
print("Merged Dataset Shape")
print(merged_df.shape)
display(merged_df.head())

Merged Dataset Shape
(1000, 30)

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,TELEPHONE,FOREIGN,RESPONSE,AMOUNT_PER_DURATION,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
0,1,6.0,0.0,0.0,0.0,1.0,0.0,0.0,1169.0,4.0,...,1.0,0.0,1.0,194.833333,0,4,4,4,4,2
1,2,48.0,0.0,0.0,0.0,1.0,0.0,0.0,5951.0,2.0,...,0.0,0.0,0.0,123.979167,1,2,0,2,2,2
2,3,12.0,0.0,0.0,0.0,0.0,1.0,0.0,2096.0,2.0,...,0.0,0.0,1.0,174.666667,3,4,0,3,3,1
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,0.0,0.0,1.0,187.666667,0,2,0,3,4,2
4,5,24.0,1.0,0.0,0.0,0.0,0.0,0.0,4870.0,3.0,...,0.0,0.0,0.0,202.916667,0,3,0,2,4,2

In [74]:
### TASK 2:- Find correlation between numerical variables.

correlation_matrix = merged_df.corr( numeric_only=True )

print("Correlation Matrix")
display(correlation_matrix)

print("Correlation with RESPONSE")
display( correlation_matrix["RESPONSE"]
        .sort_values(ascending=False))

Correlation Matrix

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,TELEPHONE,FOREIGN,RESPONSE,AMOUNT_PER_DURATION,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
OBS,1.000000,0.030324,0.058738,0.008841,-0.007529,-0.017823,-0.024465,-0.017114,0.007981,0.012601,...,0.000594,-0.018974,-0.037210,-0.013978,0.005852,-0.011691,0.003730,-0.020078,0.023697,-0.027345
DURATION,0.030324,1.000000,-0.111228,0.145838,-0.059562,-0.043652,0.003021,0.163451,0.624527,0.073696,...,0.165170,-0.139411,-0.211943,-0.125942,-0.070747,-0.075708,0.047529,0.055196,0.034497,0.213689
NEW_CAR,0.058738,-0.111228,1.000000,-0.187518,-0.259281,-0.345212,-0.127044,-0.181519,-0.038799,-0.048154,...,-0.041186,0.156039,-0.095439,0.105883,-0.068987,0.042213,-0.002736,-0.020956,0.020442,-0.089576
USED_CAR,0.008841,0.145838,-0.187518,1.000000,-0.158949,-0.211587,-0.078079,-0.111558,0.255915,-0.089643,...,0.134376,-0.031466,0.099893,0.109085,0.064733,0.038933,0.112677,0.039538,0.107677,0.180444
FURNITURE,-0.007529,-0.059562,-0.259281,-0.158949,1.000000,-0.291601,-0.107611,-0.153752,-0.037997,-0.061209,...,-0.050794,-0.009663,-0.022867,0.005086,-0.100719,-0.024526,-0.080954,-0.081938,-0.009189,0.016421
RADIO_TV,-0.017823,-0.043652,-0.345212,-0.211587,-0.291601,1.000000,-0.143411,-0.204903,-0.171473,0.137485,...,-0.080115,-0.063830,0.108934,-0.132814,0.113427,0.022792,-0.001728,0.075476,-0.091828,-0.028765
EDUCATION,-0.024465,0.003021,-0.127044,-0.078079,-0.107611,-0.143411,1.000000,-0.075517,-0.007574,0.042655,...,0.017160,-0.045300,-0.071132,-0.026190,0.007993,0.054544,0.010262,0.018153,0.041184,-0.001624
RETRAINING,-0.017114,0.163451,-0.181519,-0.111558,-0.153752,-0.204903,-0.075517,1.000000,0.100059,-0.028608,...,0.088925,-0.046820,-0.037365,-0.026646,0.021821,-0.089743,-0.018455,0.021568,-0.048221,0.001305
AMOUNT,0.007981,0.624527,-0.038799,0.255915,-0.037997,-0.171473,-0.007574,0.100059,1.000000,-0.272092,...,0.281637,-0.050463,-0.155549,0.522792,-0.043732,-0.067068,0.062493,-0.009603,0.032003,0.283011
INSTALL_RATE,0.012601,0.073696,-0.048154,-0.089643,-0.061209,0.137485,0.042655,-0.028608,-0.272092,1.000000,...,0.015276,-0.090008,-0.073559,-0.395419,-0.011092,0.044776,0.022158,0.121936,0.044640,0.094664
CO_APPLICANT,0.017953,0.028763,0.004420,-0.053618,0.060602,-0.005064,-0.047837,-0.033706,0.079098,-0.012870,...,-0.016417,0.065956,-0.063180,0.036233,-0.050982,0.007688,-0.039808,-0.036707,0.002244,0.013696
GUARANTOR,-0.004431,-0.040825,-0.012816,-0.034865,-0.027914,0.115208,-0.054130,-0.046308,-0.065664,-0.006411,...,-0.073920,0.096880,0.054994,-0.030046,-0.114815,-0.047426,-0.096000,0.007677,-0.027558,-0.070654
REAL_ESTATE,-0.038536,-0.248557,0.043835,-0.130937,-0.055155,0.127668,-0.103359,0.014621,-0.251932,-0.036792,...,-0.160580,0.112850,0.116535,-0.056968,0.032060,0.044455,-0.040924,-0.052754,-0.088132,-0.254413
PROP_UNKN_NONE,-0.015777,0.213294,0.025373,0.129952,-0.070637,-0.118435,0.155794,-0.036604,0.249812,0.045237,...,0.137365,-0.054687,-0.123057,0.118917,-0.074317,-0.025505,0.015075,0.075908,0.190376,0.154871
AGE,-0.000972,-0.036725,0.070218,0.059165,-0.129738,-0.042707,0.060078,-0.000748,0.032818,0.052671,...,0.148095,-0.005121,0.097908,0.102528,0.056829,0.140734,0.083921,0.250561,0.270274,0.015167
OTHER_INSTALL,-0.002021,0.063064,-0.032474,-0.008875,-0.002799,-0.033993,0.010185,0.096998,0.048892,0.014848,...,0.021850,-0.026150,-0.110546,-0.010821,-0.041680,-0.123330,-0.003962,0.018110,-0.017611,0.004664
RENT,0.025078,-0.060467,-0.008678,0.032944,0.109966,-0.074847,0.003123,-0.010055,-0.021982,-0.086714,...,-0.051234,0.033233,-0.092021,0.018725,-0.085661,-0.098841,-0.007305,-0.073755,0.169421,-0.033923
OWN_RES,-0.016263,-0.075505,-0.008677,-0.138206,-0.045252,0.137808,-0.102747,0.050609,-0.121523,0.047259,...,-0.033216,0.018745,0.131695,-0.056195,0.123913,0.098509,0.004678,0.004159,-0.298075,-0.063556
NUM_CREDITS,0.029534,-0.013449,0.027690,-0.002629,-0.068753,-0.029207,-0.007550,0.085577,0.021438,0.016894,...,0.060587,-0.009380,0.046197,-0.003371,0.073840,0.436126,-0.018440,0.124957,0.086759,-0.030014
NUM_DEPENDENTS,0.024881,-0.025855,0.104698,0.055555,-0.087126,-0.083941,0.042841,-0.001461,0.016582,-0.070322,...,-0.014664,0.076539,0.002179,0.086429,-0.014575,0.012868,0.027141,0.097828,0.044418,-0.096420
TELEPHONE,0.000594,0.165170,-0.041186,0.134376,-0.050794,-0.080115,0.017160,0.088925,0.281637,0.015276,...,1.000000,-0.107530,0.036227,0.143582,0.067297,0.050223,0.087425,0.061561,0.095980,0.388356
FOREIGN,-0.018974,-0.139411,0.156039,-0.031466,-0.009663,-0.063830,-0.045300,-0.046820,-0.050463,-0.090008,...,-0.107530,1.000000,0.081913,0.035026,-0.027250,0.014222,0.006527,-0.027410,-0.053385,-0.102629
RESPONSE,-0.037210,-0.211943,-0.095439,0.099893,-0.022867,0.108934,-0.071132,-0.037365,-0.155549,-0.073559,...,0.036227,0.081913,1.000000,-0.019965,0.349708,0.229500,0.179208,0.118237,-0.002747,-0.031783
AMOUNT_PER_DURATION,-0.013978,-0.125942,0.105883,0.109085,0.005086,-0.132814,-0.026190,-0.026646,0.522792,-0.395419,...,0.143582,0.035026,-0.019965,1.000000,-0.000586,0.006412,0.031329,-0.049082,0.011311,0.108401
CHK_ACCT,0.005852,-0.070747,-0.068987,0.064733,-0.100719,0.113427,0.007993,0.021821,-0.043732,-0.011092,...,0.067297,-0.027250,0.349708,-0.000586,1.000000,0.192191,0.222867,0.106339,-0.042234,0.040663
HISTORY,-0.011691,-0.075708,0.042213,0.038933,-0.024526,0.022792,0.054544,-0.089743,-0.067068,0.044776,...,0.050223,0.014222,0.229500,0.006412,0.192191,1.000000,0.039058,0.138225,0.063198,0.010350
SAV_ACCT,0.003730,0.047529,-0.002736,0.112677,-0.080954,-0.001728,0.010262,-0.018455,0.062493,0.022158,...,0.087425,0.006527,0.179208,0.031329,0.222867,0.039058,1.000000,0.120950,0.091424,0.011709
EMPLOYMENT,-0.020078,0.055196,-0.020956,0.039538,-0.081938,0.075476,0.018153,0.021568,-0.009603,0.121936,...,0.061561,-0.027410,0.118237,-0.049082,0.106339,0.138225,0.120950,1.000000,0.245081,0.101225
PRESENT_RESIDENT,0.023697,0.034497,0.020442,0.107677,-0.009189,-0.091828,0.041184,-0.048221,0.032003,0.044640,...,0.095980,-0.053385,-0.002747,0.011311,-0.042234,0.063198,0.091424,0.245081,1.000000,0.012655
JOB,-0.027345,0.213689,-0.089576,0.180444,0.016421,-0.028765,-0.001624,0.001305,0.283011,0.094664,...,0.388356,-0.102629,-0.031783,0.108401,0.040663,0.010350,0.011709,0.101225,0.012655,1.000000

Correlation with RESPONSE

RESPONSE               1.000000
CHK_ACCT               0.349708
HISTORY                0.229500
SAV_ACCT               0.179208
OWN_RES                0.131695
EMPLOYMENT             0.118237
REAL_ESTATE            0.116535
RADIO_TV               0.108934
USED_CAR               0.099893
AGE                    0.097908
FOREIGN                0.081913
GUARANTOR              0.054994
NUM_CREDITS            0.046197
TELEPHONE              0.036227
NUM_DEPENDENTS         0.002179
PRESENT_RESIDENT      -0.002747
AMOUNT_PER_DURATION   -0.019965
FURNITURE             -0.022867
JOB                   -0.031783
OBS                   -0.037210
RETRAINING            -0.037365
CO_APPLICANT          -0.063180
EDUCATION             -0.071132
INSTALL_RATE          -0.073559
RENT                  -0.092021
NEW_CAR               -0.095439
OTHER_INSTALL         -0.110546
PROP_UNKN_NONE        -0.123057
AMOUNT                -0.155549
DURATION              -0.211943
Name: RESPONSE, dtype: float64

In [75]:
#### NumPy Tasks

### Create a 3×4 NumPy array and print shape, size, dtype

array1 = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])
print(array1)

print("Shape:", array1.shape)
print("Size:", array1.size)
print("Datatype:", array1.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Size: 12
Datatype: int64

In [80]:
### Task 2:- Create arrays using zeros(), ones(), and full()

print("Zeros Array")

print(np.zeros((3,3)))

print("\nOnes Array")

print(np.ones((3,3)))

print("\nFull Array")

print(np.full((3,3), 5))

Zeros Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full Array
[[5 5 5]
 [5 5 5]
 [5 5 5]]

In [81]:
### Task 3:- Generate numbers using arange() and linspace().

print("Using arange")

print(np.arange(0,21,2))

print("\nUsing linspace")

print(np.linspace(0,100,5))

Using arange
[ 0  2  4  6  8 10 12 14 16 18 20]

Using linspace
[  0.  25.  50.  75. 100.]

In [82]:
 ### Task 4:- Create a random array and fix randomness using seed.

np.random.seed(42)

random_array = np.random.randint(
    1,
    100,
    (3,3)
)

print(random_array)

[[52 93 15]
 [72 61 21]
 [83 87 75]]

In [83]:
### Task 5:- Perform indexing (first, last, and specific element)

arr = np.array([10,20,30,40,50])

print("First Element:", arr[0])

print("Last Element:", arr[-1])

print("Specific Element:", arr[2])

First Element: 10
Last Element: 50
Specific Element: 30

In [84]:
### Task 6:- Slice a 2D array to extract a submatrix

matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

submatrix = matrix[0:2,1:3]

print(submatrix)

[[2 3]
 [6 7]]

In [85]:
### Task 7:- Reshape a 1D array into 2D array

one_d = np.arange(1,13)

two_d = one_d.reshape(3,4)

print(two_d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [86]:
### Task 8:- Perform transpose of a matrix.

matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print("Original Matrix")

print(matrix)

print("\nTranspose")

print(matrix.T)

Original Matrix
[[1 2 3]
 [4 5 6]]

Transpose
[[1 4]
 [2 5]
 [3 6]]

In [87]:
### Task 9:- Demonstrate difference between view and copy.

arr = np.array([1,2,3,4,5])

view_arr = arr.view()

copy_arr = arr.copy()

arr[0] = 100

print("Original:", arr)

print("View:", view_arr)

print("Copy:", copy_arr)

Original: [100   2   3   4   5]
View: [100   2   3   4   5]
Copy: [1 2 3 4 5]

In [88]:
### Task 10:- Reverse an array using slicing

arr = np.array([1,2,3,4,5])

reverse_arr = arr[::-1]

print(reverse_arr)

[5 4 3 2 1]